services:
  proxy:
    image: nginx
    volumes:
      - ./proxy_config.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
    depends_on:
      - backend
      - frontend
  database:
    image: postgres:15-alpine
    container_name: lavurso-database
    restart: unless-stopped
    environment:
      POSTGRES_USER: lavurso
      POSTGRES_PASSWORD: lavurso_pwd
      POSTGRES_DB: lavurso
    volumes:
      - ./data:/var/lib/postgresql/data
  backend:
    depends_on:
      - database
    container_name: lavurso-backend
    restart: unless-stopped
    build: ./lavurso-backend
    environment:
      WEB_LISTEN: 0.0.0.0:8080
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      DATABASE_USER: lavurso
      DATABASE_PASSWORD: lavurso_pwd
      DATABASE_NAME: lavurso
    # Docker image specific:
    # NO_MIGRATE=true
    # MIGRATE_TO=last
    expose:
      - 8080
  frontend:
    depends_on:
      - backend
    container_name: lavurso-frontend
    restart: unless-stopped
    build: ./lavurso-frontend
    init: true
    environment:
      API_URL: http://localhost:9000/api/ # This is your (public) back-end URL, set it to your public URL
    expose:
      - 9000
